SFA circular harmonics
spatialaudio/sfa-numpy pull request #3
Opened 2017-11-11 19:55 UTC by narahahn

* Circular array on the horizontal plane with a uniform distribution
* Radial and angular functions for plane waves and line sources (z-independent only)
* Modal analysis for plane wave decomposition

2017-11-14 13:02 UTC, trettberg commented
## CHT ordering

Currently the circular harmonics are ordered from `-N,...,0,...N`.
I think `0,...,N,-N,...,-1` would be better for consistency with the regular DFT.


## CHT scaling

IMHO the CHT should be normalized such that `FWF^H = I`, where `F` is a DFT matrix and `W` is a diagonal matrix with constant diagonal `w`.

Three possibilities:

1. `w = 1` and put `1/sqrt(M)` into `F`

2. `w = 1/M`

3. `w = 2pi/M` and put `1/sqrt(2pi)` into `F`

My personal preference would be 2.

2017-11-14 13:05 UTC, ghost requested changes

2017-11-14 13:05 UTC, trettberg commented on micarray/modal/angular.py
> +        Psi[i, :] = np.exp(1j * n * pol)
Weights are not applied!

2017-11-14 13:05 UTC, trettberg commented on micarray/modal/angular.py
> +def grid_equal_polar_angle(M, phi0=0):
The spherical grid functions take the maximum `N` as the only argument.
For consistency I'd prefer the same behavior. (i.e. pass `N` and get `2N+1` positions.)

2017-11-14 15:54 UTC, trettberg commented on micarray/modal/angular.py
> +def grid_equal_polar_angle(M, phi0=0):
@narahahn prefers the current version, being more useful in practice.
I prefer the less flexible but more consistent interface.

@spors What's your opinion?

2017-11-14 16:28 UTC, narahahn commented
* `grid_equal_polar_angle` now returns the weights of `1/M`, with `M` being the number of microphones
* The `weights` is applied to the CHT matrix in `cht_matrix`
* The order of CHT orders is changed: 0,...,N,-N,...,-1 (`cht_matrix`, `mirror_vec`)

2017-11-14 17:50 UTC, trettberg commented on micarray/modal/angular.py
> +        Matrix of spherical harmonics.
spherical -> circular

2017-11-14 17:51 UTC, trettberg commented on micarray/modal/angular.py
> +        \Psi = \left[ \begin{array}{ccccccc}
The formatting is off.

2017-11-17 16:31 UTC, ghost approved these changes

2017-11-17 17:14 UTC, merged